package com.mycompany.trabalho;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.Color;
import java.awt.Font;
import com.mycompany.trabalho.TelaPayment;


/**
 *
 * @author menezes
 */
public class CriarServicoView extends javax.swing.JFrame {

    private JComboBox<String> tipoServicoBox;
    private JTextArea descricaoTextArea;
    private JLabel precoLabel;
    private JButton pagamentoButton;

    /**
     * Creates new form CriarServicoView
     */
    public CriarServicoView() {
        initComponents();
        adicionarComponentesExtras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      private void adicionarComponentesExtras() {
        String[] servicos = {"Troca de óleo e filtros", "Alinhamento e balanceamento", "Manutenção preventiva", "Outro serviço"};
        tipoServicoBox = new JComboBox<>(servicos);
        tipoServicoBox.setBackground(Color.WHITE);
        tipoServicoBox.setFont(new Font("Arial", Font.PLAIN, 16));

        descricaoTextArea = new JTextArea(3, 20);
        descricaoTextArea.setBackground(Color.WHITE);
        descricaoTextArea.setFont(new Font("Arial", Font.PLAIN, 16));

        precoLabel = new JLabel();
        precoLabel.setForeground(Color.BLACK);
        precoLabel.setFont(new Font("Arial", Font.BOLD, 16));
        precoLabel.setVisible(false);

        pagamentoButton = new JButton("Realizar pagamento");
        pagamentoButton.setBackground(new Color(7, 41, 64));  // Azul claro para o botão
        pagamentoButton.setForeground(new Color(135, 206, 235));
        pagamentoButton.setEnabled(false);
        pagamentoButton.setFont(new Font("Arial", Font.BOLD, 14));

        getContentPane().setLayout(new java.awt.GridLayout(6, 1, 10, 10)); // Ajustando o layout com espaçamento
        JLabel escolhaServicoLabel = new JLabel("Escolha o serviço:");
        escolhaServicoLabel.setFont(new Font("Arial", Font.BOLD, 16));  // Fonte maior
        getContentPane().add(escolhaServicoLabel);

        getContentPane().add(tipoServicoBox);

        JLabel descricaoServicoLabel = new JLabel("Descrição do serviço:");
        descricaoServicoLabel.setFont(new Font("Arial", Font.BOLD, 16));  // Fonte maior
        getContentPane().add(descricaoServicoLabel);

        getContentPane().add(new JScrollPane(descricaoTextArea));
        getContentPane().add(precoLabel);
        getContentPane().add(pagamentoButton);

        tipoServicoBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                atualizarPreco();
            }
        });
        pagamentoButton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Abre a tela de pagamento
            new TelaPayment("Pedro","Revisão").setVisible(true);
            // Fecha a tela atual (CriarServicoView)
            dispose();
        }
    });

        // Definindo as cores de fundo e da janela
        getContentPane().setBackground(new Color(137, 207, 240));  // Azul escuro
        tipoServicoBox.setBackground(Color.WHITE);
        descricaoTextArea.setBackground(Color.WHITE);
        precoLabel.setBackground(new Color(137, 207, 240));  // Azul escuro para o fundo da label
        pagamentoButton.setBackground(new Color(0, 102, 204));  // Azul claro para o botão
    }

    private void atualizarPreco() {
        String selecionado = (String) tipoServicoBox.getSelectedItem();
        String preco;

        switch (selecionado) {
            case "Troca de óleo e filtros":
                preco = "Preço base: R$ 200,00";
                break;
            case "Alinhamento e balanceamento":
                preco = "Preço base: R$ 180,00";
                break;
            case "Manutenção preventiva":
                preco = "Preço base: R$ 700,00";
                break;
            default:
                preco = "Preço base: Preço variável";
                break;
        }

        precoLabel.setText(preco);
        precoLabel.setVisible(true);
        pagamentoButton.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarServicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarServicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarServicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarServicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarServicoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
